#!/usr/bin/env bash

# Function to display information about subdomains
display_info() {
    domain="$1"
    subdomain="$2"

    # If subdomain parameter is provided
    if [[ -n "$subdomain" ]]; then
        dig_output=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/{getline; print}')
        record_type=$(echo "$dig_output" | awk '{print $4}')
        destination=$(echo "$dig_output" | awk '{print $5}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        # Display information for default subdomains
        for sub in www lb-01 web-01 web-02; do
            dig_output=$(dig "$sub.$domain" | awk '/^;; ANSWER SECTION:/{getline; print}')
            record_type=$(echo "$dig_output" | awk '{print $4}')
            destination=$(echo "$dig_output" | awk '{print $5}')
            echo "The subdomain $sub is a $record_type record and points to $destination"
        done
    fi
}

# Accept domain and subdomain arguments
display_info "$1" "$2"
