#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

# Install nginx with the -y flag to avoid user prompts
apt-get update
apt-get install -y nginx

# Modify the default Nginx configuration to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Create a temporary HTML file containing "Hello World!"
echo 'Hello World!' > /var/www/html/index.html

# Restarting nginx
sudo service nginx restart
