#!/usr/bin/env bash
# Install HAproxy on clean ubuntu machine and setup to proxy requests
# between 469087-web-01 and 469087-web-02.

# Install HAProxy
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.7
apt-get update -y
apt-get -y install haproxy

# Configure HAProxy to send traffic to web-01 and web-02 using roundrobin algorithm
cat <<EOF > /etc/haproxy/haproxy.cfg
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    mode http
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 469087-web-01 35.153.98.10:80 check
    server 469087-web-02 35.153.79.136:80 check
    http-request set-header X-Served-By %[src]
EOF

# Restart HAProxy service
service haproxy restart

# Ensure HAProxy can be managed via init script
update-rc.d haproxy enable
