#!/usr/bin/env bash
# Displays "Best School but on the ninth iteration displays Hi"

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i == 9 ]; then
        echo "Hi";
    fi
    ((i++))
done
